# Site settings
title: KIM SOYEON
description: Thank you for visiting my homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://github.com/yeonsokim/soyeonkim.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SOYEON KIM
user_description: Fighting 
user_title:PORTFOLIO SITE
email: ezramatthewmiller@naver.com
# twitter_username: no
# github_username:  yeonsokim
# gplus_username: no

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
